In [38]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

data = fetch_openml('car', as_frame=True).frame
data

/home/peter/miniconda3/envs/ml-learning/lib/python3.12/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

     buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

some data sets are easier to do feature encoding with than others. in this case, stuff like lug_boot, and safety can be very easily put onto a scale. in other examples, it could be harder as something like countries dont have a natural scale. will be first doing ordinal (on a scale) encoding.

In [39]:
import numpy as np
colums_to_enconde = np.array(['lug_boot', 'safety'])


encoder = OrdinalEncoder(
    categories= [
                ['small', 'med', 'big'],
                ['low', 'med', 'high']]
)

data[colums_to_enconde] = encoder.fit_transform(data[colums_to_enconde])
data

     buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [40]:
encoder.inverse_transform(data[colums_to_enconde])
data

     buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

This covers how to encode scaling categories, now onto more sophisticated ones, we will be learning the one hot encoder?

In [41]:
data = fetch_openml('adult', as_frame=True).frame
data

/home/peter/miniconda3/envs/ml-learning/lib/python3.12/site-packages/sklearn/datasets/_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,3,United-States,>50K

In [44]:
from sklearn.preprocessing import OneHotEncoder
data.occupation.value_counts()
import pandas as pd
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False) #handle unknown decides the behaviour of when we get something we have not seen before.
encoded_values = encoder.fit_transform(data[['occupation', 'race']])
new_collumns = encoder.get_feature_names_out(['occupation', 'race'])
encoded_values
new_collumns

df_encoded = pd.DataFrame(encoded_values, columns=new_collumns, index = data.index)
data_final = pd.concat([
    df_encoded, data.drop(columns = ['occupation', 'race']
    )], axis = 1)
data_final

,occupation_Adm-clerical,occupation_Armed-Forces,occupation_Craft-repair,occupation_Exec-managerial,occupation_Farming-fishing,occupation_Handlers-cleaners,occupation_Machine-op-inspct,occupation_Other-service,occupation_Priv-house-serv,occupation_Prof-specialty,...,education,education-num,marital-status,relationship,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Bachelors,13,Never-married,Not-in-family,Male,1,0,2,United-States,<=50K
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,0,United-States,<=50K
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,HS-grad,9,Divorced,Not-in-family,Male,0,0,2,United-States,<=50K
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,11th,7,Married-civ-spouse,Husband,Male,0,0,2,United-States,<=50K
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,Bachelors,13,Married-civ-spouse,Wife,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,Bachelors,13,Divorced,Not-in-family,Female,0,0,2,United-States,<=50K
48838,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,HS-grad,9,Widowed,Other-relative,Male,0,0,2,United-States,<=50K
48839,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,3,United-States,<=50K
48840,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Bachelors,13,Divorced,Own-child,Male,2,0,2,United-States,<=50K
48841,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,3,United-States,>50K

# Summary
This chapter goes over how to encode features of the data set that are not numerical. There are two ways that were covered. First, for features that have a natural scaling, we can use OrdinaryEncoder to give each feature a level.
For non natural scaling, we can instead use One hot encoding which basically just gives you the binary represenation of what level the feature is.